name: Build
on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows --release

      - name: Zip compiled files
        run: Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath JellyOne.zip

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: JellyOne-windows-zip-x86-64
          path: JellyOne.zip

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libmpv-dev mpv

      - name: Build Linux
        run: flutter build linux --release

      - name: Zip compiled files
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: JellyOne-linux.zip
          directory: build/linux/x64/release/bundle

      - name: Upload artifact Linux zip
        uses: actions/upload-artifact@v4
        with:
          name: JellyOne-linux-zip-x86-64
          path: build/linux/x64/release/bundle/JellyOne-*.zip

  macos:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2

      - name: Build macOS
        run: flutter build macos --release

      # - name: Install create-dmg
      #   run: brew install create-dmg

      - name: Create DMG
        # run: create-dmg --volname JellyOne-macos --icon-size 100 JellyOne-macos.dmg --app-drop-link 600 185 --hide-extension build/macos/Build/Products/Release/JellyOne.app
        run: hdiutil create -volname JellyOne-macos -srcfolder build/macos/Build/Products/Release/JellyOne.app -ov -format UDZO JellyOne-macos.dmg

      - name: Upload artifact macOS DMG
        uses: actions/upload-artifact@v4
        with:
          name: JellyOne-macos.dmg
          path: JellyOne-macos.dmg
